ThinkInAIXYZ/deepchat

src/renderer/src/components/message/MessageBlockContent.vue
- disable sanitizer to enable code rendering
- fix XML code rendering
=> fix xml code rendering

src/renderer/src/lib/markdown.helper.ts
4空格会显示code_block，文字显示不清晰和出现横向滚动条
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/code.mjs
**请描述你希望的解决方案**
禁用 code_block
```
md.renderer.rules.code_block = (tokens, idx) => tokens[idx].content
```
无
**平台兼容性注意事项**
无
**附加背景**
无
=> add rendering rules

src/renderer/src/components/message/MessageBlockContent.vue
我增加了mermaid 的Preview和code切换的功能
=> Update mermaid preview

package.json, src/main/presenter/configPresenter/providers.ts, src/main/presenter/llmProviderPresenter/index.ts, src/main/presenter/llmProviderPresenter/providers/anthropicProvider.ts, src/renderer/src/components/settings/AddCustomProviderDialog.vue, src/renderer/src/components/settings/ModelProviderSettingsDetail.vue
我增加了anthropic 类型的api支持
**请描述你希望的解决方案**
支持了claude 等 anthropic 的模型
=> add support for anthropic api

package.json, src/main/contextMenuHelper.ts, src/main/presenter/windowPresenter.ts
解决了 macos上面右键菜单不随着系统语言进行刷新
解决了多次切换语言后，右键菜单存在的内存泄漏问题
=> fix context menu issue

src/main/presenter/sqlitePresenter/index.ts, src/main/presenter/threadPresenter/index.ts
=> fix files problem and artifacts problem

src/main/events.ts, src/main/index.ts, src/main/presenter/configPresenter/index.ts, src/main/presenter/proxyConfig.ts, src/renderer/src/components/settings/CommonSettings.vue, src/renderer/src/i18n/en-US.json, src/renderer/src/i18n/ja-JP.json, src/renderer/src/i18n/ko-KR.json, src/renderer/src/i18n/ru-RU.json, src/renderer/src/i18n/zh-CN.json, src/renderer/src/i18n/zh-HK.json, src/shared/presenter.d.ts
=> add custom proxy settings

src/renderer/src/components/settings/ModelProviderSettings.vue
=> 切换服务商时打开该服务商的详情页面

src/renderer/src/components/ChatView.vue, src/renderer/src/components/message/MesasgeList.vue
=> 对话框只有当用户在底部时才自动滚动

src/renderer/src/components/ChatView.vue, src/renderer/src/components/message/MesasgeList.vue
发送消息前需要滚动到底部，且将aboveThreshold置为false
=> 发送消息前需要滚动到底部，且将aboveThreshold置为false

src/main/presenter/configPresenter/index.ts, src/renderer/src/components/settings/CommonSettings.vue, src/renderer/src/i18n/zh-TW.json, src/renderer/src/main.ts
Add zh-TW Traditional Chinese locale :smile: 
新增繁體中文語系檔 :smile:
=> Add zh-TW Traditional Chinese locale

package.json
fix 'pnpm dev' need to build electron
=> update package.json to configure pnpm for built dependencies management

src/main/presenter/llmProviderPresenter/index.ts, src/main/presenter/mcpPresenter/toolManager.ts, src/main/presenter/threadPresenter/searchManager.ts
=> 记录输入到大模型的消息内容

src/renderer/src/router/index.ts, src/renderer/src/views/ChatTabView.vue, src/renderer/src/views/WelcomeView.vue
=> defer-components-load

.github/workflows/prcheck.yml, src/renderer/src/i18n/en-US/common.json
增加对于pr的check，防止无法build 的代码合并
**请描述你希望的解决方案**
增加了新的ci脚本，在合并前进行了一次buidl
=> test pr checklist

src/renderer/src/components/message/MessageItemUser.vue
=> enhance edit mode styling and functionality for message display

package.json, src/renderer/src/components/settings/ModelProviderSettings.vue, src/renderer/src/stores/settings.ts
=> allow user to order LLM providers

src/main/presenter/mcpPresenter/inMemoryServers/builder.ts, src/main/presenter/mcpPresenter/inMemoryServers/difyKnowledgeServer.ts, src/main/presenter/mcpPresenter/inMemoryServers/fastGptKnowledgeServer.ts, src/main/presenter/mcpPresenter/inMemoryServers/ragflowKnowledgeServer.ts, src/renderer/src/components/settings/DifyKnowledgeSettings.vue, src/renderer/src/components/settings/FastGptKnowledgeSettings.vue, src/renderer/src/components/settings/RagflowKnowledgeSettings.vue
=> feat: 知识库开关放到到每个具体知识库

src/main/presenter/mcpPresenter/index.ts, src/main/presenter/mcpPresenter/mcpClient.ts, src/renderer/src/components/ChatInput.vue, src/renderer/src/components/editor/mention/MentionList.vue, src/renderer/src/components/editor/mention/PromptParamsDialog.vue, src/renderer/src/components/editor/mention/suggestion.ts, src/renderer/src/components/mcp-config/mcpConfig.vue, src/renderer/src/i18n/en-US/mcp.json, src/renderer/src/i18n/fr-FR/mcp.json, src/renderer/src/i18n/ja-JP/mcp.json, src/renderer/src/i18n/ko-KR/mcp.json, src/renderer/src/i18n/ru-RU/mcp.json, src/renderer/src/i18n/zh-CN/mcp.json, src/renderer/src/i18n/zh-HK/mcp.json, src/renderer/src/i18n/zh-TW/mcp.json, src/renderer/src/stores/mcp.ts, src/shared/presenter.d.ts
修改了 Prompt 和 Resources 的 type定义，整体更加清晰
支持 Prompt 传入参数
=> add new type and better i18n

.cursor/rules/build-deploy.mdc, .cursor/rules/development-setup.mdc, .cursor/rules/error-logging.mdc, .cursor/rules/i18n.mdc, .cursor/rules/performance.mdc, .cursor/rules/project-structure.mdc, electron.vite.config.ts, package.json, src/main/presenter/llmProviderPresenter/providers/openAICompatibleProvider.ts, src/main/presenter/mcpPresenter/inMemoryServers/powerpackServer.ts, src/main/presenter/mcpPresenter/pythonRunner/index.ts, src/main/presenter/mcpPresenter/pythonRunner/prepareEnv.ts
基于 https://github.com/pyodide/pyodide 实现了简单的python运行时
=> add support for python code

src/renderer/src/components/settings/DifyKnowledgeSettings.vue, src/renderer/src/components/settings/FastGptKnowledgeSettings.vue, src/renderer/src/components/settings/RagflowKnowledgeSettings.vue
=> 知识库默认不展开 & 统一样式

src/renderer/src/components/artifacts/ArtifactDialog.vue, src/renderer/src/i18n/en-US/artifacts.json, src/renderer/src/i18n/fr-FR/artifacts.json, src/renderer/src/i18n/ja-JP/artifacts.json, src/renderer/src/i18n/ko-KR/artifacts.json, src/renderer/src/i18n/ru-RU/artifacts.json, src/renderer/src/i18n/zh-CN/artifacts.json, src/renderer/src/i18n/zh-HK/artifacts.json
=> fix(artifact): add copy button

src/main/presenter/threadPresenter/index.ts
=> fix(thread): 去除重复的generatingMessages设置

src/main/contextMenuHelper.ts, src/main/presenter/threadPresenter/index.ts, src/renderer/src/App.vue, src/renderer/src/components/ChatInput.vue, src/renderer/src/components/message/MessageContextMenu.vue, src/renderer/src/components/message/SelectedTextContextMenu.vue, src/renderer/src/components/popup/TranslatePopup.vue, src/renderer/src/i18n/en-US/contextMenu.json, src/renderer/src/i18n/en-US/index.ts, src/renderer/src/i18n/fr-FR/contextMenu.json, src/renderer/src/i18n/fr-FR/index.ts, src/renderer/src/i18n/ja-JP/contextMenu.json, src/renderer/src/i18n/ja-JP/index.ts, src/renderer/src/i18n/ko-KR/contextMenu.json, src/renderer/src/i18n/ko-KR/index.ts, src/renderer/src/i18n/zh-CN/contextMenu.json, src/renderer/src/i18n/zh-CN/index.ts, src/renderer/src/i18n/zh-TW/contextMenu.json, src/renderer/src/i18n/zh-TW/index.ts, src/shared/i18n.ts, src/shared/presenter.d.ts
请对问题进行清晰扼要的描述。
增加了 "翻译" and "问问AI" 两个邮件菜单选项：
- 翻译：点击后弹出一个窗口，使用模型做简单翻译，翻译成中文
- 问问AI：复制当前的文本到输入框，鼠标焦点聚焦在文本结尾
增加了一个可拖拽的翻译弹窗，显示文本和翻译结果
=> WIP: add "translate" and "ask ai" to context menu of selected text

src/renderer/src/components/settings/PromptSetting.vue
=> fix the css issue in multi tabs version

src/main/presenter/configPresenter/modelDefaultSettings.ts, src/main/presenter/configPresenter/providerModelSettings.ts
1. dashscope上qwen系列文字生成模型官方参数配置
2. qwen3开源模型配置没改
=> fix(modelcfg): official model configs of Qwen updated.

src/renderer/src/components/settings/PromptSetting.vue
=> fix prompt add

src/main/lib/scrollCapture.ts, src/main/presenter/index.ts, src/main/presenter/threadPresenter/index.ts, src/main/presenter/windowPresenter/index.ts, src/renderer/src/components/message/MessageItemAssistant.vue, src/renderer/src/components/message/MessageList.vue, src/shared/presenter.d.ts
- 修复了多个tab情况下，使用deeplink所有tab都会触发的问题
- 修复了窗口缩放后复制截图样式不正常的问题
- 修复了上下文拼接的时候会额外多选择一些不正确的信息
=> 多窗口的一些bug修复

src/renderer/src/components/artifacts/CodeArtifact.vue, src/renderer/src/lib/code.detect.ts
=> fix(artifacts): improve code detection accuracy

src/renderer/src/components/NewThread.vue, src/renderer/src/components/TitleView.vue
set default provider, use last provider
=> new tab set default provider

src/main/presenter/configPresenter/mcpConfHelper.ts, src/main/presenter/llmProviderPresenter/index.ts, src/main/presenter/mcpPresenter/inMemoryServers/builder.ts, src/main/presenter/mcpPresenter/inMemoryServers/deepResearchServer.ts, src/main/presenter/mcpPresenter/index.ts, src/renderer/src/i18n/en-US/mcp.json, src/renderer/src/i18n/fr-FR/mcp.json, src/renderer/src/i18n/ja-JP/mcp.json, src/renderer/src/i18n/ko-KR/mcp.json, src/renderer/src/i18n/ru-RU/mcp.json, src/renderer/src/i18n/zh-CN/mcp.json, src/renderer/src/i18n/zh-HK/mcp.json, src/renderer/src/i18n/zh-TW/mcp.json, src/renderer/src/stores/chat.ts, src/shared/presenter.d.ts
基于 https://github.com/pinkpixel-dev/deep-research-mcp 实现方式
使用bocha 搜索的 API 和内置的页面拉取能力，实现了简单的 DeepResearch
**附加背景**
目前受限于模型能力，上下文和maxtoken会极大影响最终结果
由于还没有做好分片生成后输出的能力，目前会依赖于模型最终总结的效果
=> [Feature]inmemory deep research mcp

src/main/presenter/windowPresenter/index.ts
=> fix the fullscreen close issue

shared/presenter.d.ts
=> chore: remove unuse code

src/renderer/src/views/WelcomeView.vue
=> fix: welcome component style problem

.vscode/settings.json
=> feat: add i18n-ally Custom Namespaces Match

src/renderer/src/components/TitleView.vue, src/renderer/src/views/ChatTabView.vue
closed #49 
* Are there any platform-specific behaviors or code …
=> feat: Display the model provider ID in the title bar

package.json
=> chore(markdown): upgrade vue-renderer-markdown version

src/main/presenter/configPresenter/providerModelSettings.ts
chore(modelcfg): Update deepseek-r1-0528 model config
=> chore(modelcfg): Update deepseek-r1-0528 model config

.gitignore, src/renderer/src/components/ChatInput.vue, src/renderer/src/i18n/en-US/chat.json, src/renderer/src/i18n/fr-FR/chat.json, src/renderer/src/i18n/ja-JP/chat.json, src/renderer/src/i18n/ko-KR/chat.json, src/renderer/src/i18n/ru-RU/chat.json, src/renderer/src/i18n/zh-CN/chat.json, src/renderer/src/i18n/zh-HK/chat.json, src/renderer/src/i18n/zh-TW/chat.json
=> Support paste files

src/main/events.ts, src/main/index.ts, src/main/presenter/index.ts, src/main/presenter/tabPresenter.ts, src/main/presenter/windowPresenter/index.ts
fix(ui): 调整tray生命周期管理；修正win11下窗口缩放恢复后tab无显示的bug，添加restore逻辑
注意：
1、只fix了windows下的ui行为：tray和窗口缩放，mac os待测，请合并者确认
2、其中代码跟github oauth做了merge，但是无法测，请合并者确认
=> fix(ui): Adjust tray lifecycle management; fix Win11 tab display after zoom restore

src/renderer/src/components/settings/PromptSetting.vue
https://github.com/user-attachments/assets/24a5c4dc-9e1e-42e6-b292-4a2f25faef1e
=> style: fix prompt dialog scroll

src/main/presenter/configPresenter/index.ts, src/main/presenter/configPresenter/providerModelSettings.ts, src/main/presenter/configPresenter/providers.ts, src/main/presenter/configPresenter/shortcutKeySettings.ts, src/main/presenter/githubCopilotDeviceFlow.ts, src/main/presenter/githubCopilotOAuth.ts, src/main/presenter/llmProviderPresenter/oauthHelper.ts, src/main/presenter/llmProviderPresenter/providers/githubCopilotProvider.ts, src/main/presenter/mcpPresenter/inMemoryServers/deepResearchServer.ts, src/main/presenter/oauthPresenter.ts, src/main/presenter/shortcutPresenter.ts, src/renderer/src/components/TitleView.vue, src/renderer/src/components/message/MessageList.vue, src/renderer/src/components/settings/GitHubCopilotOAuth.vue, src/renderer/src/views/ChatTabView.vue
参考了新的思路进行了重构
**请描述你希望的解决方案**
目前还缺失一个完整报告输出的能力，内存里面的中间态数据利用率还不是很高
=> Refactor deepresearch

src/main/presenter/mcpPresenter/inMemoryServers/deepResearchServer.ts
=> feat(dsearch): support self-driven retrieval with confidence scoring and incremental reflection evaluation

package.json, src/renderer/src/components/artifacts/CodeArtifact.vue
=> fix: update vue-renderer-markdown dependency to version 0.0.25 to fix katex lost style## Pull Request Description

src/main/events.ts, src/main/presenter/mcpPresenter/inMemoryServers/conversationSearchServer.ts, src/main/presenter/sqlitePresenter/tables/conversations.ts, src/main/presenter/tabPresenter.ts, src/main/presenter/threadPresenter/index.ts, src/renderer/src/components/ThreadsView.vue, src/renderer/src/components/settings/ShortcutSettings.vue, src/renderer/src/events.ts, src/renderer/src/stores/chat.ts
* feat(agent): MCP agentic multi-tab control, future-ready architecture
* refactor(ui/event): consolidate chat events & tab updates for race-free, resilient UX
* Migrates to a unidirectional broadcast model, ensuring reliable state across tabs and laying groundwork for next-gen agentic features and multi-session workflows of multi-chatbot agents.
=> feat(agent): enable robust MCP agentic control for multi-tab environments

src/renderer/src/components/ChatInput.vue, src/renderer/src/lib/searchHistory.ts
=> feat(ChatInput): implement search history functionality with navigation support

package.json
=> feat: update vue-renderer-markdown deps support dir auto

src/main/events.ts, src/main/index.ts, src/main/presenter/trayPresenter.ts, src/renderer/src/stores/upgrade.ts, src/shared/i18n.ts
=> feat: tray menu check version

src/main/presenter/llmProviderPresenter/providers/dashscopeProvider.ts
add dashscope commercial models to enable_thinking support
=> feat: add dashscope commercial models to enable_thinking support
